language: node_js
node_js:
  - '8'
  - '10'
  - '11'
script:
  - yarn run lint
  - yarn run check-fmt
  - yarn run test-cover
after_success:
  - yarn run coverage
notifications:
  flowdock: $FLOWDOCK_API_TOKEN
