language: node_js
node_js:
- '8'
- '10'
- '11'
script:
- yarn run lint
- yarn run check-fmt
- yarn run tsc
- yarn run test-cover
after_success:
- yarn run coverage
notifications:
  slack:
    secure: vuBp7KKQqHax5B/9NS7D8GiedcpLPXrfe7gzsyDow89rcqv6O6dtePzF1QtujsCVExRYNhApgCSb+cA30aHaJih6sQ9F3/suPSa1ql1AbpNmpxuQFFGO2LiRIHQ5cFMiBpvr4vP/nK3emwdRukKNmVgVcikYUCmJhrEXaL2YvCWq2amZj8pe/r2PCaeHknG2hVsJGhEHIxAwGqBtQQGI+z65MWebSAdLnmdPAoGDYfHRMKyhkFrF0BDsrCFOWRp/AoZ4rr6oqTZ7h97wTRKTNXoVcBoFp2dvXOuA3xuWrQvGFAIWdgkUwRHrN0ALuGy6/vZLhGldcKgvhQtEXCXeBCb/JQ15MjaUaxtcpUxkcZ/kHObqe1XXdbZbhGImkdg4ea7IH4H0pCzRyGieBbH63Mb0Pu46UCqAmCjjeKYPsSa3dOPXBHc48AP/zS1QrBxYeH7GwHmQZN4L39g2POWLu5Td0FfIIiDB/Y9ryE87mRkLFE0IGpFT+DlWGII1L75kgs673DFwbyuOGSoBUKdEV6TcGEmE4ExitBQwjwfDiZLY1ouL1WlTbcj84X9ou4idlCxBGScaaR/E4ddwEMH8C8C/QMRlpDQLyRJYH6PP1S7T8XCr7LHvLxaMn0C8TcRaXo0m8UdSy3kcWvAUCvgVXAngTZE1fzRELN4IaELwwfY=
